### ISSUE TITLE
Change the git configs to FF-only and no merge commits?

### ISSUE THREAD

**Issue by itay-sho** [gregsadetsky/recurse-rfid-visits#2]
will give us a significantly better git history :) (opinion)

**Comment by gregsadetsky** [comment]
yes sorry for being so lazy about this haha!

perfect, I ran `git config --global pull.ff only` I should be good to go!!

**Comment by itay-sho** [comment]
Awesome! I would recommend changing Github's repo setting to be a different merge strategy, (I don't really like merge commits 👎 ) again - just an opinion and would like to discuss if you have a different one!

**Comment by gregsadetsky** [comment]
disabled merged commits!

<img width="538" alt="image" src="https://github.com/gregsadetsky/recurse-rfid-visits/assets/1017304/892cec45-16c9-4a7f-95c4-191e60db4a19">

let me know if it works / let's check!
