### ISSUE TITLE
document how to ssh into raspberry pi

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/recurse-rfid-visits#8]
maybe just include ssh pi@(address..?) into the public docs

and say to ping you or me for the password?

just so that that we don't forget how to do it

**Comment by itay-sho** [comment]
because it's a public repo I don't want to put the pi's password here
where do you think we can put it?

maybe there's a wiki or something?

**Comment by gregsadetsky** [comment]
yeah we can use the RC wiki for the password for sure -- we could create a page about signing in under https://github.com/recursecenter/wiki/wiki#other

**Comment by itay-sho** [comment]
Ok I created a wiki page for checkintopus here:
https://github.com/recursecenter/wiki/wiki/Checkintopus
there is still more work to do there but we have the basics 👍 

also created a PR here to reference to the wiki from info about the deployment / rpi password etc.

my philosophy about the wiki (and code docs in general) - if possible it should always be in the repo.
so it means that I would prefer to doc only deployment & confidential stuff on recurse wiki.
your opinion?

**Comment by gregsadetsky** [comment]
absolutely agreed re: docs/wiki public/private! I also don't like deduplicating docs, and it's nice to have this project be public :-)

we'll add a minimal amount of info in the wiki. great!
